#!/bin/sh

# NO TODOs
pattern="^+.*TODO"
if git commit -v --dry-run | grep $pattern > /dev/null 2>&1
then
  msg="# Warning: TODOs found in commit!"
  file=$(tempfile)
  (echo $msg; cat $1) > $file
  mv $file $1
fi
